-- First, ensure slots has a uuid column with unique constraint
ALTER TABLE public.slots ADD COLUMN IF NOT EXISTS uuid UUID;
UPDATE public.slots SET uuid = gen_random_uuid() WHERE uuid IS NULL;

-- Add unique constraint (if not exists, will error but that's ok)
ALTER TABLE public.slots ADD CONSTRAINT slots_uuid_unique UNIQUE (uuid);

-- Now create watch_specs table
CREATE TABLE IF NOT EXISTS public.watch_specs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  watch_id UUID REFERENCES public.slots(uuid) ON DELETE CASCADE,
  brand TEXT, collection TEXT, model_name TEXT, reference_number TEXT, nickname TEXT, sku TEXT, upc_ean TEXT, country_of_origin TEXT, manufacturer TEXT, designer TEXT, release_year INTEGER, production_start_year INTEGER, production_end_year INTEGER, limited_edition BOOLEAN DEFAULT false, limited_quantity INTEGER, serial_number TEXT, certificate_number TEXT, watch_classification TEXT,
  watch_type TEXT, dress BOOLEAN DEFAULT false, diver BOOLEAN DEFAULT false, pilot BOOLEAN DEFAULT false, field BOOLEAN DEFAULT false, racing BOOLEAN DEFAULT false, gmt BOOLEAN DEFAULT false, tool BOOLEAN DEFAULT false, smartwatch BOOLEAN DEFAULT false, tactical BOOLEAN DEFAULT false, luxury BOOLEAN DEFAULT false, sports BOOLEAN DEFAULT false, casual BOOLEAN DEFAULT false, gender_target TEXT, style TEXT, era_vintage TEXT, intended_use TEXT, collection_theme TEXT,
  case_material TEXT, case_coating TEXT, case_finish TEXT, brushed BOOLEAN DEFAULT false, polished BOOLEAN DEFAULT false, sandblasted BOOLEAN DEFAULT false, dlc BOOLEAN DEFAULT false, pvd BOOLEAN DEFAULT false, case_diameter_mm DECIMAL, case_thickness_mm DECIMAL, lug_to_lug_mm DECIMAL, lug_width_mm INTEGER, weight_grams DECIMAL, case_shape TEXT, round BOOLEAN DEFAULT false, square BOOLEAN DEFAULT false, cushion BOOLEAN DEFAULT false, tonneau BOOLEAN DEFAULT false, rectangular BOOLEAN DEFAULT false, octagonal BOOLEAN DEFAULT false, crown_type TEXT, screw_down BOOLEAN DEFAULT false, push_pull BOOLEAN DEFAULT false, crown_guards BOOLEAN DEFAULT false, crown_position TEXT, helium_escape_valve BOOLEAN DEFAULT false, exhibition_caseback BOOLEAN DEFAULT false, open_caseback BOOLEAN DEFAULT false, solid_caseback BOOLEAN DEFAULT false, screw_down_caseback BOOLEAN DEFAULT false, snap_caseback BOOLEAN DEFAULT false, monobloc_case BOOLEAN DEFAULT false, water_resistance_meters INTEGER, shock_resistance BOOLEAN DEFAULT false, magnetic_resistance BOOLEAN DEFAULT false, anti_magnetic_certification TEXT,
  crystal_material TEXT, sapphire BOOLEAN DEFAULT false, mineral BOOLEAN DEFAULT false, acrylic BOOLEAN DEFAULT false, crystal_shape TEXT, flat BOOLEAN DEFAULT false, domed BOOLEAN DEFAULT false, double_domed BOOLEAN DEFAULT false, anti_reflective_coating BOOLEAN DEFAULT false,
  bezel_type TEXT, bezel_material TEXT, bezel_action TEXT, fixed BOOLEAN DEFAULT false, unidirectional BOOLEAN DEFAULT false, bidirectional BOOLEAN DEFAULT false, bezel_insert_material TEXT, bezel_color TEXT,
  dial_color TEXT, dial_finish TEXT, sunburst BOOLEAN DEFAULT false, matte BOOLEAN DEFAULT false, gloss BOOLEAN DEFAULT false, textured BOOLEAN DEFAULT false, fume BOOLEAN DEFAULT false, enamel BOOLEAN DEFAULT false, dial_material TEXT, dial_pattern TEXT, dial_layout TEXT, indices_type TEXT, applied BOOLEAN DEFAULT false, printed BOOLEAN DEFAULT false, roman BOOLEAN DEFAULT false, arabic BOOLEAN DEFAULT false, baton BOOLEAN DEFAULT false, lume_type TEXT, lume_color TEXT, hands_style TEXT, hands_color TEXT, seconds_hand_type TEXT, chapter_ring BOOLEAN DEFAULT false, rehaut_type TEXT, dial_features TEXT, open_heart BOOLEAN DEFAULT false, skeletonized_dial BOOLEAN DEFAULT false, california_dial BOOLEAN DEFAULT false, sandwich_dial BOOLEAN DEFAULT false, logo_placement TEXT, date_window_position TEXT, cyclops_lens BOOLEAN DEFAULT false, subdial_count INTEGER, subdial_layout TEXT,
  movement_brand TEXT, movement_manufacturer TEXT, movement_model TEXT, movement_type TEXT, automatic BOOLEAN DEFAULT false, manual BOOLEAN DEFAULT false, quartz BOOLEAN DEFAULT false, solar BOOLEAN DEFAULT false, kinetic BOOLEAN DEFAULT false, spring_drive BOOLEAN DEFAULT false, smart BOOLEAN DEFAULT false, movement_origin TEXT, jewels_count INTEGER, beat_rate_vph INTEGER, frequency_hz DECIMAL, power_reserve_hours INTEGER, accuracy_rating TEXT, cosc_certified BOOLEAN DEFAULT false, metas_certified BOOLEAN DEFAULT false, chronometer BOOLEAN DEFAULT false, movement_decoration TEXT, hacking_seconds BOOLEAN DEFAULT false, hand_winding BOOLEAN DEFAULT false, rotor_type TEXT, escapement_type TEXT, balance_spring_material TEXT, movement_thickness_mm DECIMAL, movement_diameter_mm DECIMAL, battery_type TEXT, battery_life_years INTEGER, service_interval_years INTEGER, service_cost_estimate DECIMAL,
  time_only BOOLEAN DEFAULT false, date_complication BOOLEAN DEFAULT false, day_date BOOLEAN DEFAULT false, big_date BOOLEAN DEFAULT false, gmt_complication BOOLEAN DEFAULT false, world_time BOOLEAN DEFAULT false, dual_time BOOLEAN DEFAULT false, chronograph BOOLEAN DEFAULT false, flyback_chronograph BOOLEAN DEFAULT false, split_seconds BOOLEAN DEFAULT false, moonphase BOOLEAN DEFAULT false, perpetual_calendar BOOLEAN DEFAULT false, annual_calendar BOOLEAN DEFAULT false, power_reserve_indicator BOOLEAN DEFAULT false, alarm BOOLEAN DEFAULT false, minute_repeater BOOLEAN DEFAULT false, tourbillon BOOLEAN DEFAULT false, tachymeter BOOLEAN DEFAULT false, pulsometer BOOLEAN DEFAULT false, telemeter BOOLEAN DEFAULT false, dive_timer BOOLEAN DEFAULT false, regatta_timer BOOLEAN DEFAULT false, compass_bezel BOOLEAN DEFAULT false, tide_indicator BOOLEAN DEFAULT false, heart_rate_sensor BOOLEAN DEFAULT false, bluetooth BOOLEAN DEFAULT false, gps BOOLEAN DEFAULT false, nfc BOOLEAN DEFAULT false,
  strap_type TEXT, bracelet BOOLEAN DEFAULT false, leather_strap BOOLEAN DEFAULT false, nato BOOLEAN DEFAULT false, rubber BOOLEAN DEFAULT false, fabric BOOLEAN DEFAULT false, silicone BOOLEAN DEFAULT false, strap_material TEXT, strap_color TEXT, strap_width_mm INTEGER, bracelet_construction TEXT, oyster BOOLEAN DEFAULT false, jubilee BOOLEAN DEFAULT false, president BOOLEAN DEFAULT false, milanese BOOLEAN DEFAULT false, end_links_type TEXT, solid_end_links BOOLEAN DEFAULT false, quick_release BOOLEAN DEFAULT false, quick_adjust_clasp BOOLEAN DEFAULT false, clasp_type TEXT, pin_buckle BOOLEAN DEFAULT false, deployant BOOLEAN DEFAULT false, butterfly BOOLEAN DEFAULT false, folding BOOLEAN DEFAULT false, clasp_material TEXT, clasp_finish TEXT, taper_width_mm INTEGER, bracelet_screws BOOLEAN DEFAULT false, female_end_links BOOLEAN DEFAULT false, strap_interchangeability BOOLEAN DEFAULT false, max_wrist_size_mm INTEGER, min_wrist_size_mm INTEGER,
  total_weight_grams DECIMAL, head_weight_grams DECIMAL, wrist_presence TEXT, wearability_notes TEXT, thickness_perception TEXT, cuff_compatibility BOOLEAN DEFAULT false, ergonomics_rating INTEGER,
  depth_rating_meters INTEGER, iso_certification TEXT, iso_6425_compliant BOOLEAN DEFAULT false, anti_shock_system BOOLEAN DEFAULT false, anti_magnetic_level TEXT, operating_temperature TEXT, lume_duration_hours INTEGER, water_test_date DATE, timing_results TEXT, positional_accuracy TEXT,
  msrp DECIMAL, currency TEXT, launch_price DECIMAL, current_market_price DECIMAL, used_market_price DECIMAL, investment_rating TEXT, value_retention TEXT, availability TEXT, discontinued BOOLEAN DEFAULT false, dealer_network TEXT, grey_market BOOLEAN DEFAULT false, collectibility TEXT, rarity TEXT, historical_importance TEXT, iconic_status TEXT, celebrity_association TEXT, military_issue BOOLEAN DEFAULT false, limited_edition_number TEXT, special_edition_type TEXT, collaboration TEXT, auction_record TEXT, desirability_score INTEGER,
  condition_grade TEXT, box_included BOOLEAN DEFAULT false, papers_included BOOLEAN DEFAULT false, warranty_included BOOLEAN DEFAULT false, last_serviced_date DATE, running_condition TEXT, timegrapher_readings TEXT, scratches BOOLEAN DEFAULT false, crystal_damage BOOLEAN DEFAULT false, bezel_wear BOOLEAN DEFAULT false, stretch_in_bracelet BOOLEAN DEFAULT false,
  cover_image_url TEXT, video_review_url TEXT, youtube_links TEXT, official_brand_url TEXT, manual_pdf_url TEXT, marketing_description TEXT, editorial_review TEXT, user_review_score DECIMAL, tags TEXT, seo_slug TEXT,
  created_by TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_by TEXT, updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.watch_specs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read watch_specs" ON public.watch_specs FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Auth users can modify watch_specs" ON public.watch_specs FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT ALL ON public.watch_specs TO anon, authenticated, service_role;